import { FileBlob, SpreadsheetFile } from "@oai/artifact-tool";
const root = "C:/performance_geral_cjm/00 - HTML's update";
const path = `${root}/outputs/01a08633-89b4-7283-8814-f0b65f6970f7/ParametrosOperacionais_Inbound.xlsx`;
const workbook = await SpreadsheetFile.importXlsx(await FileBlob.load(path));
const sheet = workbook.worksheets.getItem("Jornada");
sheet.getRange("G7").values = [[17 / 24]];
workbook.recalculate();
const check = await workbook.inspect({ kind: "table", range: "Jornada!A6:K8", include: "values,formulas", tableMaxRows: 3, tableMaxCols: 11 });
console.log(check.ndjson);
const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(`${path}.fixed`);
